[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Match the baud rate in your C++ code
monitor_speed = 115200

; Automatically download the MPU6050_light library
lib_deps = 
    rfetick/MPU6050_light @ ^1.1.0
